#!/usr/bin/env bash
#This script receives signal from another script and prints a message 

msg()
{
	echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done 
