#!/usr/bin/env bash
# This script displays "Holberton School" 10 times

x=0
while (( x < 10));
do
	if (( x == 3 ))
	then 
		echo "bad luck"
	elif (( x == 7 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( x++ ));
done
