#!/usr/bin/env bash
# This script displays "Holberton School" 10 times

x=1
while (( x < 21));
do
	if (( x == 4 ))
	then 
		echo $x
		echo "bad luck from China"
	elif (( x == 9 ))
	then
		echo $x
		echo "bad luck from Japan"
	elif (( x == 17 ))
	then
		echo $x
		echo "bad luck from Italy"
	else
		echo $x
	fi
	(( x++ ));
done
