#!/usr/bin/env bash
# This script displays "Holberton School" 10 times

x=1
while (( x < 21));
do
	echo "$x"
	case $x in
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
	(( x++ ))
done
