#!/usr/bin/env bash
# This script that configures an Ubuntu server and changes localhost and facebook.com 12.0.0.2 and 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost/127.0.0.2 localhost/g'  ~/hosts.new
sed -i 's/.*facebook.com//g' ~/hosts.new
sed -i '1 a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
